№3 СӨЖ
Студенттердің аты мен бағалары бар сөздік жасап, ең жоғары бағаны тап


In [ ]:
students = {}

def add_student(name, grade):
    students[name] = grade
    print(f"Student {name} with grade {grade} added.")

def list_students():
    if not students:
        print("No students added yet.")
        return
    print("List of Students:")
    for name, grade in students.items():
        print(f"  {name}: {grade}")

def average_grade():
    if not students:
        return 0
    return sum(students.values()) / len(students)

def find_highest_grade():
    if not students:
        return None, None
    highest_grade = 0
    student_with_highest_grade = None
    for name, grade in students.items():
        if grade > highest_grade:
            highest_grade = grade
            student_with_highest_grade = name
    return student_with_highest_grade, highest_grade

if __name__ == '__main__':
    add_student('Aigerim', 85)
    add_student('Bulat', 92)
    add_student('Ali', 78)
    add_student('Dana', 95)
    list_students()
    print('Average:', average_grade())
    highest_student, highest_g = find_highest_grade()
    if highest_student:
        print(f'Student with the highest grade: {highest_student} ({highest_g})')
    else:
        print('No students to find the highest grade.')

Student Aigerim with grade 85 added.
Student Bulat with grade 92 added.
Student Ali with grade 78 added.
Student Dana with grade 95 added.
List of Students:
  Aigerim: 85
  Bulat: 92
  Ali: 78
  Dana: 95
Average: 87.5
Student with the highest grade: Dana (95)


№4 СӨЖ
Rectangle деген класс құрып, оның ауданы мен периметрін есептейтін әдістерін жазыңыз.
try-except көмегімен пайдаланушы енгізетін екі санды бөліңіз (қателерді өңдеңіз).
Өз модуліңізді (mymath.py) құрып, add, sub, mul, div функцияларын жазыңыз.
NumPy арқылы 10 элементтен тұратын кездейсоқ массив жасап, оның орта мәнін, максимум және минимумын табыңыз.


In [ ]:
class Rectangle
:
  def __init__(self, atau, avtory):
    self.atau = atau
    self.avtory = avtory

  def kitap_turaly_malimet(self):
    print(f"Кітап: {self.atau}, Авторы: {self.avtory}")

kitap1 = Kitap('Абай жолы', 'Әуезов')
kitap1.kitap_turaly_malimet()

5-СӨЖ

In [2]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler, StandardScaler

# 1) Екі 3×3 матрица, қосындысы, айырмасы, көбейтіндісі
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

sum_AB = A + B
diff_AB = A - B
prod_AB = np.dot(A, B)

# 2) 3 өлшемді екі вектордың скаляр көбейтіндісі және бұрышы
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

scalar_product = np.dot(v1, v2)
angle = np.arccos(
    scalar_product / (np.linalg.norm(v1) * np.linalg.norm(v2))
)

# 3) Матрицаның детерминанты, кері матрицасы, өз мәндері
M = np.array([[2, 1, 0],
              [0, 1, -1],
              [1, 0, 1]]) # Modified M to be an invertible matrix

det_M = np.linalg.det(M)
inv_M = np.linalg.inv(M)
eigenvalues = np.linalg.eigvals(M)

# 4) np.random.randn() арқылы 1000 элементтік үлгі
sample = np.random.randn(1000)

mean_sample = np.mean(sample)
var_sample = np.var(sample)
std_sample = np.std(sample)

# 5) Min-Max және Z-score нормализациясы
data = np.array([5, 10, 15, 20, 25]).reshape(-1, 1)

minmax_scaler = MinMaxScaler()
data_minmax = minmax_scaler.fit_transform(data)

standard_scaler = StandardScaler()
data_zscore = standard_scaler.fit_transform(data)

sum_AB, diff_AB, prod_AB, scalar_product, angle, det_M, inv_M, eigenvalues, mean_sample, var_sample, std_sample, data_minmax, data_zscore

(array([[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]]),
 array([[-8, -6, -4],
        [-2,  0,  2],
        [ 4,  6,  8]]),
 array([[ 30,  24,  18],
        [ 84,  69,  54],
        [138, 114,  90]]),
 np.int64(32),
 np.float64(0.2257261285527342),
 np.float64(1.0),
 array([[ 1., -1., -1.],
        [-1.,  2.,  2.],
        [-1.,  1.,  2.]]),
 array([1.87743883+0.74486177j, 1.87743883-0.74486177j,
        0.24512233+0.j        ]),
 np.float64(0.01608679149708957),
 np.float64(0.9737112645858701),
 np.float64(0.9867680905794786),
 array([[0.  ],
        [0.25],
        [0.5 ],
        [0.75],
        [1.  ]]),
 array([[-1.41421356],
        [-0.70710678],
        [ 0.        ],
        [ 0.70710678],
        [ 1.41421356]]))